microsoft/Microsoft-UI-UIAutomation

- src/UIAutomation/FunctionalTests/FunctionalTests.cpp
- src/UIAutomation/FunctionalTests/pch.h
- src/UIAutomation/Microsoft.UI.UIAutomation/AutomationRemoteOperation.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/AutomationRemoteOperation.h
- src/UIAutomation/Microsoft.UI.UIAutomation/Client.g.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/MessageBuilder.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/MessageBuilder.h
- src/UIAutomation/Microsoft.UI.UIAutomation/Microsoft.UI.UIAutomation.idl
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructionSerialization.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructionSerialization.h
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructions.h
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.g.h
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.h
The platform implementation of remote operations now supports a GUID operand type and instructions for working with this type. These additions are necessary when working with UIA extensions such as custom properties and the upcoming support for custom annotations. This PR exposes the new GUID type and related instructions in the high-level WinRT builder API and adds test coverage at that level.
> Expose GUID instructions in the WinRT builder API

- README.md
- build/Install-WindowsSdkISO.ps1
- src/UIAutomation/Microsoft.UI.UIAutomation/Microsoft.UI.UIAutomation.vcxproj
- src/UIAutomation/SharpConsoleAppDemo/SharpConsoleAppDemo.csproj
- src/UIAutomation/UIAutomation.sln
In order to enable automatic CI in Azure Pipelines, we need to ensure that the appropriate version of the Insider Preview SDK is installed on the build machine. This is achieved by the new `Install-WindowsSdkISO` script. This is the same approach that other projects use, for instance `microsoft-ui-xaml`.
The PR also fixes an issue with build order/dependency for the C# demo app: it now explicitly depends on the `Microsoft.UI.UIAutomation` project (since it needs the metadata produced by this step). The `Windows.winmd` file that was referenced when `Microsoft.UI.UIAutomation.winmd` itself was built is copied to the same output directory just to make sure that all projects wind up referencing all the same metadata.
Closes #7
> Enable Azure Pipelines build validation

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
This commit adds an implementation of `UiaChar` -- a wrapper around
`Microsoft.UI.UIAutomation.AutomationRemoteChar` in the same style as
all other "abstraction" wrappers. The local equivalent of this type is
`wchar_t`. This required the general plumbing for converting results to
local values as well as converting local values to remote operands.
This new `UiaChar` type is then used to implement `UiaString::At`, a
method that allows character-level indexing of `UiaString`. The ability
to index remote strings is supported by the UIA platform (Remote
Operations VM) as well as the builder library, so this is just an
addition to the abstraction library.
Resolves #12
> Add UiaChar and UiaString indexing

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
`winrt::Microsoft::UI::UIAutomation::AutomationRemoteRect` has full support for reading `X`, `Y`, `Width` and `Height` of rectangle properties and attributes. However, `UiaRect` defined by the UIA operation abstraction library does not give access to the these qualities of rectangles.
This change adds the missing support for the rectangle members/qualities to `UiaRect`.
The support allows implementing heuristics around rectangles and the areas they cover (such as Win32's `IsRectEmpty`) through the abstraction library types and operations.
Resolves #15
> Add support for accessing UIA rectangle dimensions to `UiaRect`

- src/UIAutomation/FunctionalTests/WinRTBuilderTests.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/Microsoft.UI.UIAutomation.idl
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.h
Remote arrays can be compared for equality in the underlying Remote
Operations VM. This PR exposes this functionality via the builder methods.
Notably, this allows Runtime Ids to be compared more efficiently than before.
(Previously, it was _possible_, but the Remote Op itself needed to implement
element-by-element comparison, which would count against the instruction
limit, waste time at runtime, as well as was more complex than it really should
be for an important and relatively common thing.)
> AutomationRemoteArray: Add equality comparison methods

- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
The UiaHwnd class has the conversion operator declared in the header file, which aims to be used to get to the local type from the abstraction type. But the implementation is not in place, so the client of operation abstraction such as Narrator will get the linking error while building DLLs since the implementation is missing in the static lib.
This change adds the simple implementation here to get the local type.
> UiaHwnd: Add implementation of conversion operator to UIA_HWND

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
The ability of achieving array comparison was recently added in remote operation implementation. This PR wires up array comparison in the abstraction wrapper so that client such as Narrator could use it in a convenient way.
> Add array comparison in the abstraction wrapper

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/Microsoft.UI.UIAutomation.idl
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructionSerialization.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructionSerialization.h
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructions.h
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.h
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
**Remote Operations** provide a variety of types that can be used to perform more complex calculations on the provider side. The types range from "simple" numeric types, collections (arrays, maps) to UIA proprietary types (elements, text ranges).
UIA clients often times have to work with the UIA tree, analyze it and perform operations based on relationships between elements in the tree. However, there is no "simple" way of creating and remembering the relationships/associations in **Remote Operations** today.
That is because Remote Operations provide 2 different collection types:
1. Flat arrays,
2. Maps from strings to any object type (supported by UIA).
(2) would be ideal to remember relationships between elements. However, UIA elements identify themselves through `RuntimeId`s that are …
> Add support for `Stringify` operations to UIA operation abstraction

- src/UIAutomation/FunctionalTests/WinRTBuilderTests.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/AutomationRemoteAnyObjectMethods.g.h
- src/UIAutomation/Microsoft.UI.UIAutomation/AutomationRemoteOperationMethods.g.h
- src/UIAutomation/Microsoft.UI.UIAutomation/Client.g.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/Microsoft.UI.UIAutomation.idl
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructionSerialization.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructionSerialization.h
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructions.h
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.g.h
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.h
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstractionEnums.g.h
This PR adds support for `GetMetadataValue` to the WinRT Builder library.
The first part of the PR is adding the `AutomationMetadata` enum to the WinRT surface area. This is done by running the (currently still closed-source) code generator to generate all the relevant pieces for an enum based on the information in the classic COM typelib.
The `GetMetadataValue` method added to `AutomationRemoteElement` is then a simple wrapper around the underlying platform Remote Operations VM bytecode instruction, which follows the existing pattern of builder wrappers.
A functional end-to-end test is added, but only for a provider that doesn't support metadata currently (Xaml). The (currently still closed-source) larger test suite in the OS does validate the underlying instruction against providers …
> WinRT Builder: Add GetMetadataValue support

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/Microsoft.UI.UIAutomation.idl
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.h
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstraction.g.h
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstractionImpl.g.cpp
`IUIAutomationElement` allows UIA clients to request elements (new objects) with fresh/updated cache information. As it is right now, the UIA operation abstraction library does not support this operation.
The change closes the gap by:
1. Adding `AutomationRemoteElement::GetUpdatedCacheElement` that creates a new element register, sets it to the element to rebuild and then requests to populate its cache with the provided cache request (input),
2. Adding `UiaElement::GetUpdatedCacheElement` to provide the functionality of creating new, rebuilt elements for local and remote operations through the UIA operation abstraction.
The change adds a test that verifies the functionality.
Fixes #26
> Add support for `IUIAutomationElement::BuildUpdatedCache` to the UIA operation abstraction library

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
Today, iterating over and working with a collection of elements in a `UiaArray` is a relatively verbose process that requires from the code author to create a full-fledged `For` loop that takes multiple lambda expressions (initialize, break condition, post-loop increment and the body of the loop) and variables (size of the collection, element index and collection element).
To make the process smoother, this change adds 3 proposed (in the linked work items) improvements to the UIA operation abstraction library:
* `ContinueIf` that is an equivalent of an `If` statement that -- if met -- skips over the currently processed loop iteration (`continue`),
* `BreakIf` which is a complementary concept to the first one that -- instead of `continue`-ing past the current loop iteration -- `break`s the …
> Add `ForEach`, `ContinueIf` and `BreakIf` to the UIA operation abstraction library

- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
Currently, in order to create a `UiaRect` or `UiaPoint` variables, the code author has to specify the exact values to initialize the variables with. The need of initializing the two types with explicit values creates unnecessarily verbose code in common situations where the types should simply be there, default-initialized and ready to use for upcoming value assignments and calculations.
This change attempts to simplify the situation by adding default constructors for the two types to initialize them with:
1. An empty rectangle in case of `UiaRect`,
2. `POINT(0 /* X */, 0 /* Y */)` in case of `UiaPoint`.
Fixes #27
> Add default initialization for `UiaRect` and `UiaPoint` to empty values

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
Currently, when using the UIA operation abstraction library, inputs and results can only be bound to the operation scope one by one. While the functionality is absolutely sufficient to define remote operations with any number of input arguments and output/result values, it creates unnecessarily long, repeating patterns of chains of `BindInput` and `BindResult` calls.
The change adapts the proposed (in the issue) solution for it by adding variadic `BindInput` and `BindResult`. It also modifies one of the tests to use the new version of `BindResult`.
Fixes #5
> Add an ability to multi-bind input and result variables via UIA operation abstraction

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
`winrt::Windows::Foundation::Rect ConvertRect(RECT rect)` is a helper created to convert from Win32 `RECT` to `WinRT` `winrt::Windows::Foundation::Rect` for the purpose of creating `UiaRect` out of the commonly used `RECT` type.
However, currently, the helper incorrectly passes the left and top coordinates of `RECT` as `Height` and `Width` of `winrt::Rect` due to which the resulting `winrt::Rect`s returned by the helper are not correct.
The change fixes the problem by correcting the order of constructor arguments.
Fixes #25
> Fix `ConvertRect` to correctly convert `RECT` to `winrt::Windows::Foundation::Rect`

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstraction.g.h
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstractionImpl.g.cpp
The UIA operation abstraction library provides tools that make writing UIA-based calls both more efficient, more modern, but also executable in a local context (where all UIA calls are separate cross-process calls) and in a remote context (send the entire operation to the application in a one cross-process call and execute the operation there).
To account for both types of contexts, property getters on `UiaElement` and `Uia*` pattern classes provide a flag (`useCachedApi`) that allows switching between getting properties from the element cache or asking for a fresh (current) value.
That option is invaluable when converting existing UIA-based functionalities to using the abstraction library as it allows preserving the pre-conversion performance characteristic of the functionalities. …
> Default `useCachedApi` to `false` for property and pattern getters of `UiaElement` and pattern classes of the UIA operation abstraction library

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
`UiaEnum` is a wrapper type that can be constructed out of the following types:
1. COM `enum`s such as `CONTROLTYPEID` (local type),
2. WinRT `enum`s of the operation builder such as `AutomationControlType` (local type),
3. Corresponding stand-in (numeric) type (remote type),
4. `UiaEnum` itself (copy-construction).
The abstraction class is providing 3 different types of comparison methods against the mentioned values depending on what the caller has. In short, `UiaEnum` allows comparing against COM, WinRT `enum`s as well as the `UiaEnum` type (the abstraction tries to hide the corresponding stand-in type).
However, this does not work today due to ambiguity of defined comparison operators (and which should be applied for which situation/type).
In fact, the only comparison operators that …
> Fix `UiaEnum` comparison operators for all types `UiaEnum` can be constructed out of

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
To enable putting items in `UiaArray` and `UiaStringMap` (as values, not keys), a wrapper type has to:
1. Provide a constructor that takes the wrapper's local type (such as `std::shared_ptr<std::vector<T>>` in case of `UiaArray`),
2. Provide a constructor that takes the remote type (such as `AutomationRemoteArray` for `UiaArray`s),
3. Provide cast definitions to desired types (`c_anyTest` and `c_anyCast`) to let the collections determine collection element types.
4. Conversion operator from the wrapper type to the local type (such as the already `std::shared_ptr<std::vector<T>>` type in case of `UiaArray`).
Currently, neither `UiaArray` nor `UiaStringMap` meet the requirements and therefore they cannot be used as element types of other collections.
While the situations of nesting …
> Add necessary constructs to `UiaArray` and `UiaStringMap` to enable nesting the collections in other collections

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
Currently, UIA operation abstraction and its wrappers give access to:
1. Primitive types (`int`, `bool`, `uint`, `double`, character, ...),
2. Variants,
3. Enums (`COM`, `WinRT`),
4. UIA types (element, patterns, rectangle...),
5. Strings,
6. Some collections (arrays, maps from string to other types).
The library does not provide support for any `struct`-like types. The closest it gets to that is through collections of variants.
This change attempts to add support for `UiaTuple` to mimic C++'s `std::tuple` and to provide more tools to work with types that provide access to multiple fields of different value types.
First and foremost, the change adds `UiaTuple` to the collection of types that the library offers. As with other wrappers, the class is a variant of two types:
1. Local, which …
> Add support for `UiaTuple` to the UIA operation abstraction library

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/FunctionalTests/pch.h
- src/UIAutomation/UiaOperationAbstraction/SafeArrayUtil.cpp
- src/UIAutomation/UiaOperationAbstraction/SafeArrayUtil.h
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.vcxproj
- src/UIAutomation/UiaOperationAbstraction/pch.h
This was causing name collision issues when ingesting this into the OS
repo. Effectively, we probably shouldn't be exposing internal utilities
of this library into the root namespace.
This change also includes creating a basic SafeArrayUtil.cpp and
adding more things to the pch.
> Put safe array utilities under their own namespace

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstractionImpl.g.cpp
The remote operation abstraction wrapper has various navigation methods which are implemented with two steps, first these navigation methods will perform navigation operation, such _GetParentElement_, _GetNextSiblingElement_, next, the returned element is directly used to populate cache when a cache request is passed in. But between first step and second step, the implementation fails to check if the returned element is null or not, which could result in the unexpected failure when the  remote operation is operated on the provider side, this PR fixes this issue by adding nullity check in these functions.
Fixes #51
> Fix navigation method missing nullity check before using cache request

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/FunctionalTests/pch.h
- src/UIAutomation/UiaOperationAbstraction/SafeArrayUtil.h
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
- src/UIAutomation/UiaOperationAbstraction/pch.h
The change reorganizes some of `#include`s in `/src/UIAutomation/UiaOperationAbstraction` to self-contain `UiaOperationAbstraction.h` and allow consuming the header without including other headers.
Similar efforts have been made around `SafeArrayUtil.h`.
Fixes #53
> Self-contain `UiaOperationAbstraction.h` for easier consumption

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstraction.g.h
The `UiaStringMap` is a template class that support different wrapper types as the value of map. Since this is a template class, the corresponding instantiated class used as value need to implement all necessary function or variable to pass the compile time. The `LookUp` function in `UiaStringMap` requires the class used as value has function pointer `c_anyCast` variable defined so that we could cast the `AutomationRemoteAnyObject` to specific value class object. Unfortunately, classes in our generated files, such as `UiaElement`, are missing `c_anyCast` defined which resulted in the compiling errors when `UiaStringMap` used to hold class like `UiaElement` as value. 
This PR fixes the issue by adding missed defined variable.
> Add any cast in element and pattern class

- src/UIAutomation/Microsoft.UI.UIAutomation/Microsoft.UI.UIAutomation.idl
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructionSerialization.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructionSerialization.h
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructions.h
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.g.h
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.h
This PR adds client builder apis for the Extensibility work that is introduced recently. Adds Builder APIs for two functionalities CallExtension and IsExtensionSupported. These methods are added to a new class AutomationRemoteExtensionTarget which is extended by AutomationRemoteElement and AutomationRemoteTextRange respectively.
> Client Builder APIs for Extensibility work

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstraction.g.h
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstractionEnums.g.h
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstractionImpl.g.cpp
The reason for making this change is to make the wrapper supports get metadata value functionality.
Therefore, a helper is added `UiaVariant GetMetadataValue(UiaPropertyId propertyId, UiaMetadata metadataId);`
Once we get the returned `UiaVariant`, the proper usage is to cast this to the exact enum type we want (for example `UiaSayAsInterpretAs`). However, this cast is not supported in the wrapper yet. Also, `UiaVariant::IsNull()` is added, otherwise cannot really use the returned value.
To address the cast issue from `UiaVariant` to `UiaEnum`, an update is made to the `UiaEnum` definition to include a `CastFunc` template parameter. The type of this function is defined as:
`StandinT (winrt::Microsoft::UI::UIAutomation::AutomationRemoteAnyObject::*)() const`.
After adding `CastFunc`, we …
> Update enum and metadata wrapper

- README.md
- src/UIAutomation/FunctionalTests/FunctionalTests.vcxproj
- src/UIAutomation/Microsoft.UI.UIAutomation/Microsoft.UI.UIAutomation.vcxproj
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.vcxproj
Currently this project targets the specific Windows SDK preview 10.0.19613.0.
Not only is this sdk now very old, it is quite a headache for 3rd party projects to integrate this project, being forced to use that specific sdk.
The vc++ projects (functional tests, Microsoft.UI.UIAutomation library, and abstraction API) all now target the latest Windows 10 SDK, rather than being hard coded to 10.0.19613.0.
For each of the vcxxproj files, this involved:
* changing WindowsTargetPlatFormVersion from 10.0.19613.0 to 10.0. VS 2019 supports this value as meaning the latest Windows 10 sdk version.
* Find all references to 10.0.19613.0 (there were many hard-coded paths containing this) and replace them with $(TargetPlatformVersion), which expands to the actual latest Windows 10 sdk full version …
> Target the [latest] Windows SDK rather than hard coding to 10.0.19613.0

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
Because we cannot construct a UiaEnum from an AutomationRemoteAnyObject, UiaEnum currently cannot be included as part of a UiaTuple type. This PR adds this constructor for UiaEnum and makes proper tests for this function.
Closes #65
> Let UiaEnum can be part of UiaTuple

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
There is no explicit reason to avoid UiaTuple make move assignments.
But UiaTuple cannot just get the inherent function from UiaTypeBase.
This PR defines the move assignment operator and move constructor for UiaTuple explicitly.
Closes #66
> Add explicit move assignment operator for UiaTuple

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstraction.g.h
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstractionImpl.g.cpp
UiaOperationAbstraction's UiaElement class currently has getter methods for most if not all standard UIA properties (E.g. GetName, GetControlType etc). However, there is no way to cleanly fetch a property value by a given property ID. Exposing GetPropertyValue would be useful for the following reasons:
* Calling logic may want to fetch a long list of properties. Rather than having to hard-code calls to the individual getter methods, it would be much easier to just walk through a for loop of property IDs, calling GetPropertyValue generically with each property ID.
* UI Automation has the concept of custom properties, and Microsoft products seem to be moving towards using these more heavily these days. Assuming that Microsoft.UI.UIAutomation.AutomationRemoteElement.GetPropertyValue and its …
> UiaOperationAbstraction: expose GetPropertyValue as a method on UiaElement

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstraction.g.h
UiaOperationAbstraction has a UiaVariant type for storing data of many types. This is very useful inconjunction with the UiaArray or UiaStringMap types, allowing for holding collections of data of varying types.
Although all the basic data types (UiaInt, UiaString, UiaBool etc) are supported by UiaVariant, UiaElement is not. Meaning that it is impossible to store a UiaElement in a UiaArray or UiaStringMap of variants.
this pr allows constructing a UiaVariant given a UiaElement as its constructor argument. UiaVariant also now exposes an IsElement method for checking if the variant is holding a UiaElement, and an AsElement method, which allows for fetching the UiaElement as a UiaElement.
This work involved:
* Adding the appropriate helper members to UiaElement for partispating in UiaVariant …
> UiaOperationAbstraction:  allow converting a UiaElement to a UiaVariant and back again 

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/FunctionalTests/pch.h
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
- src/UIAutomation/UiaOperationAbstraction/pch.h
This PR add the Try/Catch helpers in UiaOperationAbstraction wrappers. It also add a helper for GetCurrentFailureCode.
> Add support for TryBlock and CatchBlock in UiaOperationAbstraction wrapper

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/FunctionalTests/WinRTBuilderTests.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/AutomationRemoteOperation.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/AutomationRemoteOperation.h
- src/UIAutomation/Microsoft.UI.UIAutomation/Microsoft.UI.UIAutomation.idl
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
IsOpcodeSupported is an API provided by CoreAutomationRemoteOperation
which determines whether a given remote operation opcode is supported by
the current provider connection. Which opcodes are supported depends on
both the client and provider UIA versions.
This change simply plumbs IsOpcodeSupported through
Microsoft.UI.UIAutomation and UiaOperationAbstraction. A more elegant
design taking advantage of the characteristics of each wrapper can be
made in the future.
For UiaOperationAbstraction, we always return true from
IsOpcodeSupported in the local case.
Note, IsOpcodeSupported will throw E_FAIL on future versions of Windows
when no connection has yet been established. Once such versions of
Windows are released, we should update tests and comments with the
specifics. This is tracked by …
> Add IsOpcodeSupported support to WinRT and C++ wrappers

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
In UiaOperationAbstraction, we use a few special exceptions for local
control flow:
- `ReturnSuccessException` is used to emulate the `Halt` instruction
when the current operation status is `S_OK`.
- `LoopContinueException` is used to continue loops.
- `LoopBreakException` is used to break out of loops.
Since these exceptions are used for control flow by
UiaOperationAbstraction and don't represent errors, we don't want
`TryCatch` or `Try` to catch them.
This change also fixes a couple test bugs. A large opcode is reduced to
fit into a `uint32_t`, and `InitializeUiaOperationAbstraction` is now
called at the beginning of every test to prevent stale global data from
the previous test accidentally being used.
Closes #76
> Allow special exceptions to pass through try-catch blocks

- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
This PR fixes bug in remote operation wrapper implementation that a crash could occur that when remote UiaArray is nullptr.
> Add nullptr check to remote UiaArray result

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.h
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.vcxproj
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstraction.g.h
- src/UIAutomation/UiaOperationAbstraction/UiaTypeAbstractionImpl.g.cpp
UI Automation recently introduced the concept of custom patterns. This is the ability for a provider to expose custom methods, identified by a GUID, that a client an execute via UIA remote Operations. For example, MS Word might expose a custom pattern for moving by sentence - something that UIA by itself does not support.
This PR implements the ability for a client to execute these custom methods (extensions) by using the UIA Operation Abstraction library. Support for custom patterns has already been introduced to the Microsoft::UI::UIAutomation winrt library.
Specific changes:
* Added a new UiaGuid class, which represents either a local or remote GUID.
* It can be constructed locally from a winrt::guid.
* It can be assigned to, and compaired with == / !=.
* It exposes …
> UIA Operation Abstraction lib: implement support for CallExtension / IsExtensionSupported

- src/UIAutomation/Microsoft.UI.UIAutomation/AutomationRemoteAnyObjectMethods.g.h
- src/UIAutomation/Microsoft.UI.UIAutomation/AutomationRemoteOperation.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/AutomationRemoteOperation.h
- src/UIAutomation/Microsoft.UI.UIAutomation/Client.g.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/Microsoft.UI.UIAutomation.idl
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructionSerialization.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructionSerialization.h
- src/UIAutomation/Microsoft.UI.UIAutomation/RemoteOperationInstructions.h
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.cpp
- src/UIAutomation/Microsoft.UI.UIAutomation/Standins.h
This PR implements all the wrappers specific to Custom Extensions. This includes ConnectionBoundObject wrappers, Byte/ByteArray wrappers and other wrappers specific to custom extensions.
> Implement wrappers for CustomExtensions

- src/UIAutomation/FunctionalTests/UiaOperationAbstractionTests.cpp
- src/UIAutomation/UiaOperationAbstraction/UiaOperationAbstraction.cpp
In pr #91, new exceptions were raised by scope.Resolve such as InstructionLimitExceeded and UnhandledException. In the case of InstructionLimitExceeded, any result variables already calculated before the limit was hit will be still resolved, making them available locally. 
This pr now resolves any possible variables for UnhandledException as well.
This now means that it is possible to track the progress of a remote operation either via remote logging for example, and even if an UnhandledException is raised from a COM call, or deliberately through a call to AbortOperationWithHresult, the variable/s holding the remote logging will still be available.
This then enables the pattern of failing fast in a remote operation much nicer, as you can just abort at any point but still have access to …
> UIA Operation Abstraction library: resolve any results alredy available before a remote unhandled exception
